spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/Cafehub
    username: sa
    password:
    driver-class-name: org.h2.Driver


  jpa:
    hibernate:
      ddl-auto: create


    properties:
      hibernate:
        format_sql: true


logging.level:
  org.hibernate.SQL: debug


jwt:
  secret: aBcD3FgH1JkLmN6PqR9sTuV2xYzZ4Xw7ZCXcDsf34sSDaF2KLE233fdsFWEefF325ggJK436lkGsGgkGJ9w43lk

kakao:
  restapi-key: 0ee2193a048d38e5d783af58eac76e36
  redirect-url: http://localhost:3000/OAuthCallback

cloud:
  aws:
    s3:
      bucket: idontknow

springdoc:
  packages-to-scan: com.cafehub                                     # API 문서를 생성할 컨트롤러 클래스가 포함된 패키지 지정
  default-consumes-media-type: application/json;charset=UTF-8       # API가 기본적으로 소비하는 미디어 타입, 우리는 JSON
  default-produces-media-type: application/json;charset=UTF-8       # API가 기본적으로 생성하는 미디어타입,  우리는 JSON
  swagger-ui:
    path: /swagger                               # Swagger UI의 경로 지정, 루트경로에 Swagger UI 표시 도메인/swagger
    disable-swagger-default-url: true            # 기본 swagger 경로 비활성화, swagger-ui/index.html
    display-request-duration: true               # 요청 지속 시간을 표시할지 여부를 설정합니다. API 요청에 대한 응답 시간 같은걸 볼 수 있음
    operations-sorter: alpha                     # Swagger UI에서 작업을 정렬하는 방법을 지정합니다. 알파벳 순
