## 임시 DB  H2 , 실제 DB 연결 안함

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/
    username: sa
    password:
    driver-class-name: org.h2.Driver


  jpa:
    hibernate:
      ddl-auto: update


    properties:
      hibernate:
        format_sql: true


logging.level:
  org.hibernate.SQL: debug


server:
  servlet:
    session:
      timeout: 1800